import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { PasswordProvider, PasswordModal } from "../app/components/PasswordProtection";
import SmoothScrollProvider from "../app/components/SmoothScrollProvider";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata = {
  title: "Valen Masijmo Designer T-Shirt's & Hoodies | Valen Masijmo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <PasswordProvider>
          <SmoothScrollProvider>
            {children}
          </SmoothScrollProvider>
          <PasswordModal />
        </PasswordProvider>
      </body>
    </html>
  );
}